### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by kievechua** [dockerfile/mongodb#1]
I set it up using `docker pull dockerfile/mongodb`

Then I start it up with `docker run -d -p 27017:27017 -p 28017:28017 dockerfile/mongodb --rest`

But when I run `docker run -i -rm -t -entrypoint="mongo" dockerfile/mongodb`
it throw following error

```
MongoDB shell version: 2.4.9
connecting to: test
Mon Mar 10 04:14:40.180 Error: couldn't connect to server 127.0.0.1:27017 at src/mongo/shell/mongo.js:145
exception: connect failed

[error] client.go:2245 Couldn't send EOF: use of closed network connection
```

Is this a bug or I'm doing something wrong?

**Comment by jayzeng** [comment]
I am getting the same error, @kievechua have you found a workaround?

**Comment by mjo09a** [comment]
It's not a bug.  It should try and connect at 0.0.0.0:27017.  Same goes for when you run a mysql docker and try to connect.  I just do not know how to change that for mongo

**Comment by kothar** [comment]
It seems that you need to tell mongo to connect to the host: the default connection is to 127.0.0.1, which is inside the second container and not the same interface as 127.0.0.1 on the host. If you force it to connect to the IP address of the host, it connects as expected.

**Comment by dharmi** [comment]
run "docker inspect &lt;container_id&gt;" which produces a JSON result.  Look for "IPAddress" under "NetworkSettings" and submit the below command
"mongo --port &lt;port number/27017&gt; --host &lt;IPAddress from the JSON response&gt;"
