### ISSUE TITLE
Upgrade build to include 2.6.4 release

### ISSUE THREAD

**Issue by drazzib** [dockerfile/mongodb#11]
Hi,

From Docker Hub build history [1], it seems that this trusted build has not been updated to lastest release in 2.6.x series (which is 2.6.4 as of now). It would be great to trigger a rebuild of this recipe so that latest Debian package is used.

PS: For sake of readability, maybe it would be great to force version inside apt-get instruction and always push a tagged version in Docker Hub.

[1] https://registry.hub.docker.com/u/dockerfile/mongodb/builds_history/6862/

**Comment by drazzib** [comment]
FTR, MongoDB 2.6.1 release actually available on Docker Hub is affected by this important performance regression : https://jira.mongodb.org/browse/SERVER-13675

**Comment by pilwon** [comment]
@drazzib Rebuilt for v2.6.4. We'll look into tagging too.
