### ISSUE TITLE
Container will not run

### ISSUE THREAD

**Issue by projectweekend** [dockerfile/mongodb#6]
When attempting to run `docker run -d -p 27017:27017 dockerfile/mongodb` I receive "Invalid command: bash" error with an output of general options. Output from `docker version`:

Client version: 0.11.1
Client API version: 1.11
Go version (client): go1.2.1
Git commit (client): fb99f99
Server version: 0.11.1
Server API version: 1.11
Git commit (server): fb99f99
Go version (server): go1.2.1
Last stable version: 0.11.1

**Comment by pilwon** [comment]
@projectweekend Please try again with the latest version. `docker pull dockerfile/mongodb`

**Comment by projectweekend** [comment]
Everything is back to normal. Thanks @pilwon!
